- hosts: all
  tasks:
    - name: Copy the artifact
      copy:
        src: /var/lib/jenkins/workspace/myapp/main
        dest: /home/ubuntu/main
        mode: 0755

    - name: Create a unit file
      become: True
      copy:
        src: myapp.service
        dest: /etc/systemd/system/myapp.service

    - name: Open port 4444 in firewall
      become: True
      community.general.ufw:
        rule: allow
        port: '4444'
        proto: tcp
      ignore_errors: yes

    - name: Start the service
      become: True
      ansible.builtin.systemd:
        name: myapp.service
        daemon_reload: true
        state: started

