- hosts: all
  tasks:
    - name: Copy index.js 
      copy:
        src: /var/lib/jenkins/workspace/myapp/index.js
        dest: /home/laborant/index.js
        mode: 0755

    - name: Copy package.json
      copy:
        src: /var/lib/jenkins/workspace/myapp/package.json
        dest: /home/laborant/package.json
        mode: 0644

    - name: Add NodeSource Node.js 24 repo
      become: True
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
      args:
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: Install Node.js 24
      become: True
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install packages
      npm:
        path: /home/laborant
        production: yes

    - name: Create a unit file
      become: True
      copy:
        src: /var/lib/jenkins/workspace/myapp/target/myapp.service
        dest: 
          /etc/systemd/system/myapp.service

    - name: Start the service
      become: True
      ansible.builtin.systemd:
        name: myapp.service
        daemon_reload: true
        state: started
